import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {createApplication,configuration} from '../apps/server/app.mjs';
import {mac} from '../apps/server/security.mjs';
let app,base,a,b,pair,playerToken,tvId,manifest,scanId;
async function request(path,{who=a,body,method,token,csrf=true}={}){
  const headers={};if(who?.cookie){headers.Cookie=who.cookie;headers['X-Venue-Id']=who.venue; if(csrf)headers['X-CSRF-Token']=who.csrf;}
  if(token)headers.Authorization=`Bearer ${token}`;
  if(body!==undefined)headers['Content-Type']='application/json';
  const r=await fetch(base+'/api'+path,{method:method||(body!==undefined?'POST':'GET'),headers,body:body!==undefined?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),headers:r.headers};
}
async function signup(email,name){const r=await request('/auth/signup',{who:null,body:{name,email,password:'correct-horse-test-password',venueName:name+' Venue',type:'golf',timezone:'America/Chicago'}});assert.equal(r.status,201,JSON.stringify(r.data));const who={cookie:r.headers.get('set-cookie').split(';')[0],venue:r.data.venueId};const s=await request('/session',{who});who.csrf=s.data.csrf;who.user=s.data.user.id;return who;}
async function webhook(path,body,secret){const raw=JSON.stringify(body),t=Math.floor(Date.now()/1000),r=await fetch(base+'/api/hooks/'+path,{method:'POST',headers:{'Content-Type':'application/json',[path==='stripe'?'Stripe-Signature':'X-Mixx-Signature']:`t=${t},v1=${mac(secret,`${t}.${raw}`)}`},body:raw});return {status:r.status,data:await r.json()};}
before(async()=>{const config=configuration({DB_PATH:':memory:',DEMO_MODE:'true',APP_SECRET:'x'.repeat(40),FREE_TV_LIMIT:'5',COMMISSION_BPS:'1000',COMMERCE_WEBHOOK_SECRET:'test-commerce',STRIPE_WEBHOOK_SECRET:'test-stripe',STRIPE_PRICE_PAID:'price_paid',STRIPE_PRICE_PREMIUM:'price_premium'});app=createApplication({config,stripe:async()=>({id:'sub_test',metadata:{venue_id:a.venue},customer:'cus_test',status:'active',items:{data:[{price:{id:'price_paid'},quantity:7}]}})});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${app.server.address().port}`;app.config.APP_ORIGIN=base;a=await signup('a@example.com','Alpha');b=await signup('b@example.com','Beta');});
after(async()=>await app.close());
test('unauthenticated venue data is blocked',async()=>assert.equal((await request('/venue',{who:null})).status,401));
test('tenant isolation rejects another venue ID',async()=>{const r=await request('/venue',{who:{...b,venue:a.venue}});assert.equal(r.status,404);});
test('CSRF is required for authenticated mutations',async()=>{const r=await request('/venue',{body:{name:'hijacked'},method:'PATCH',csrf:false});assert.equal(r.status,403);});
test('untrusted Origin is rejected even with valid cookies',async()=>{const r=await fetch(base+'/api/venue',{method:'PATCH',headers:{Cookie:a.cookie,'Content-Type':'application/json','X-Venue-Id':a.venue,'X-CSRF-Token':a.csrf,Origin:'https://evil.example'},body:'{"name":"evil"}'});assert.equal(r.status,403);});
test('MIXX and theme persist in database',async()=>{const r=await request('/venue',{method:'PATCH',body:{theme:'speakeasy',mix:{mode:'blend',worlds:{golf:'more',bourbon:'less'},minutes:180,seed:4,subcategories:{}}}});assert.equal(r.status,200);const state=await request('/venue');assert.equal(state.data.venue.theme,'speakeasy');assert.equal(state.data.venue.mix.worlds.golf,'more');});
test('pairing returns pending before it is claimed',async()=>{const r=await request('/player/pair',{who:null,body:{}});assert.equal(r.status,201);pair=r.data;playerToken=pair.deviceToken;const pending=await request('/player/pair/'+pair.id,{who:null,token:pair.pollToken});assert.equal(pending.data.status,'pending');});
test('claiming code pairs a TV, reuse is blocked, no fake online status',async()=>{const claim=await request('/tvs/claim',{body:{code:pair.code,name:'Main Bar',group:'Bar TVs'}});assert.equal(claim.status,201);tvId=claim.data.tvId;const twice=await request('/tvs/claim',{body:{code:pair.code,name:'Duplicate'}});assert.equal(twice.status,400);const state=await request('/venue');assert.equal(state.data.tvs[0].online,false);const paired=await request('/player/pair/'+pair.id,{who:null,token:pair.pollToken});assert.equal(paired.data.status,'paired');});
test('heartbeat updates online state and real cache counters',async()=>{const r=await request('/player/heartbeat',{who:null,token:playerToken,body:{cacheSeconds:60,cacheBytes:12345,playing:true,title:'Test'}});assert.equal(r.status,200);const v=await request('/venue');assert.equal(v.data.tvs[0].online,true);assert.equal(v.data.tvs[0].cache_bytes,12345);});
test('foreign TV commands are rejected and valid commands require ack',async()=>{assert.equal((await request('/commands',{who:b,body:{ids:[tvId],kind:'pause'}})).status,404);assert.equal((await request('/commands',{body:{ids:[tvId],kind:'pause'}})).status,200);const state=await request('/player/state',{who:null,token:playerToken});assert.equal(state.data.commands[0].kind,'pause');assert.equal((await request('/player/ack',{who:null,token:playerToken,body:{id:state.data.commands[0].id}})).status,200);assert.equal((await request('/player/state',{who:null,token:playerToken})).data.commands.length,0);});
test('viewer role cannot control TVs',async()=>{app.db.run('INSERT INTO members VALUES(?,?,?)',a.venue,b.user,'viewer');const r=await request('/commands',{who:{...b,venue:a.venue},body:{ids:[tvId],kind:'play'}});assert.equal(r.status,403);});
test('admin actions cannot be accessed by normal venue operators',async()=>assert.equal((await request('/admin')).status,403));
test('draftless demo catalog is explicit and manifest has real context',async()=>{app.db.run("UPDATE users SET platform_role='admin' WHERE id=?",a.user);assert.equal((await request('/admin/demo-content',{body:{}})).status,201);const result=await request('/player/manifest',{who:null,token:playerToken});assert.equal(result.status,200,JSON.stringify(result.data));manifest=result.data;assert.ok(manifest.items.length>0);assert.equal(manifest.items.reduce((n,i)=>n+i.playSeconds,0),10800);assert.match(manifest.items[0].qrUrl,/\/r\//);assert.equal(manifest.items[0].demo,true);});
test('unchanged current programming reuses its issued manifest and QR context',async()=>{const r=await request('/player/manifest',{who:null,token:playerToken});assert.equal(r.data.id,manifest.id);assert.equal(r.data.items[0].qrUrl,manifest.items[0].qrUrl);});
test('playback events are deduplicated, bounded, and tenant scoped',async()=>{const item=manifest.items[0],e={id:crypto.randomUUID(),manifestId:manifest.id,contentId:item.contentId,campaignId:null,playbackId:crypto.randomUUID(),kind:'tick',seconds:5,occurredAt:Date.now()};const r=await request('/player/events',{who:null,token:playerToken,body:{events:[e]}});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.accepted.length,1);await request('/player/events',{who:null,token:playerToken,body:{events:[e]}});assert.equal(app.db.get('SELECT count(*) n FROM events').n,1);const bad=await request('/player/events',{who:null,token:playerToken,body:{events:[{...e,id:crypto.randomUUID(),seconds:999}]}});assert.equal(bad.data.rejected.length,1);});
test('hardware requests reject non-five/ten terms and remain pending',async()=>{assert.equal((await request('/contracts',{body:{years:7,tvs:2}})).status,400);const r=await request('/contracts',{body:{years:5,tvs:2}});assert.equal(r.status,201);const c=app.db.get('SELECT * FROM contracts WHERE venue_id=?',a.venue);assert.equal(c.status,'requested');assert.equal(c.signed_ref,'');});
test('promotions and schedules actually persist',async()=>{assert.equal((await request('/promotions',{body:{kind:'event',title:'Friday dinner',description:'Ask your host',startsAt:Date.now()-1000,endsAt:Date.now()+86400000}})).status,201);const r=await request('/schedules',{body:{name:'Dinner',start:'18:00',end:'21:00',days:[1,2],mix:{mode:'single',worlds:{bourbon:'normal'},minutes:180,seed:1},theme:'speakeasy',tvIds:[tvId]}});assert.equal(r.status,201);const state=await request('/venue');assert.equal(state.data.promotions.length,1);assert.equal(state.data.schedules.length,1);});
test('QR requires consent before creating a scan',async()=>{const code=manifest.items[0].qrUrl.split('/').at(-1);assert.equal((await request('/public/scans',{who:null,body:{code,age21:false,consent:false}})).status,400);const r=await request('/public/scans',{who:null,body:{code,age21:true,consent:true}});assert.equal(r.status,200);scanId=r.data.scanId;assert.ok(scanId);});
test('settled order ledger is idempotent and refund adjusts rather than edits history',async()=>{let body={eventId:'order_evt1',orderId:'merchant_order1',scanId,netMerchandiseCents:10000,refundedCents:0,currency:'USD',status:'settled'};assert.equal((await webhook('order',body,'test-commerce')).status,200);assert.equal((await webhook('order',body,'test-commerce')).data.duplicate,true);body={...body,eventId:'refund_evt1',refundedCents:2500,status:'refunded'};assert.equal((await webhook('order',body,'test-commerce')).status,200);assert.equal(app.db.get('SELECT SUM(amount_cents) total FROM ledger').total,750);assert.equal(app.db.get('SELECT COUNT(*) n FROM ledger').n,2);assert.throws(()=>app.db.run('UPDATE ledger SET amount_cents=1'),/append-only/);const metrics=(await request('/venue')).data.metrics;assert.equal(metrics.earnedCents,750);assert.equal(metrics.salesCents,7500);assert.equal(metrics.balanceCents,750);});
test('forged order webhook and older refund snapshots are rejected',async()=>{const body={eventId:'bad',orderId:'merchant_order1',scanId,netMerchandiseCents:10000,refundedCents:0,currency:'USD',status:'settled'};assert.equal((await webhook('order',body,'wrong-secret')).status,401);assert.equal((await webhook('order',body,'test-commerce')).status,409);});
test('subscription entitlements update only after a verified webhook',async()=>{assert.equal((await request('/venue')).data.venue.plan,'free');const body={id:'evt_sub',type:'customer.subscription.updated',data:{object:{id:'sub_test'}}};assert.equal((await webhook('stripe',body,'test-stripe')).status,200);const venue=(await request('/venue')).data.venue;assert.equal(venue.plan,'paid');assert.equal(venue.seats,7);});
test('brand reports reject venue accounts and scope brand records',async()=>{assert.equal((await request('/brands',{who:b})).status,403);app.db.run("UPDATE users SET platform_role='brand',brand_id='other-brand' WHERE id=?",b.user);assert.equal((await request('/brands',{who:b})).data.campaigns.length,0);});
test('paired TV allowance is enforced on the server',async()=>{for(let n=0;n<4;n++){const p=await request('/player/pair',{who:null,body:{}});assert.equal((await request('/tvs/claim',{who:b,body:{code:p.data.code,name:'Seat '+n}})).status,201);}const p=await request('/player/pair',{who:null,body:{}});assert.equal((await request('/tvs/claim',{who:b,body:{code:p.data.code,name:'Last free seat'}})).status,201);const tooMany=await request('/player/pair',{who:null,body:{}});assert.equal((await request('/tvs/claim',{who:b,body:{code:tooMany.data.code,name:'One too many'}})).status,409);});
test('revoked TV credentials no longer read state',async()=>{assert.equal((await request('/tvs/'+tvId,{method:'PATCH',body:{revoke:true}})).status,200);assert.equal((await request('/player/state',{who:null,token:playerToken})).status,401);});
