import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {createApplication,configuration} from '../apps/server/app.mjs';
let app,base,owner,other,requestId;
async function req(path,body,who=owner,csrf=true){const headers={};if(who){headers.Cookie=who.cookie;headers['X-Venue-Id']=who.venue;if(csrf)headers['X-CSRF-Token']=who.csrf;}if(body!==undefined)headers['Content-Type']='application/json';const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json(),headers:r.headers};}
async function signup(name){const r=await req('/api/auth/signup',{name,email:name.toLowerCase()+'@music.example',password:'test-music-password-long',venueName:name+' Venue',type:'golf'},null);assert.equal(r.status,201);const who={venue:r.body.venueId,cookie:r.headers.get('set-cookie').split(';')[0]};const s=await req('/api/session',undefined,who);who.csrf=s.body.csrf;who.id=s.body.user.id;return who;}
before(async()=>{app=createApplication({config:configuration({DB_PATH:':memory:',SIGNUPS_ENABLED:'true',APP_SECRET:'music-tests-not-a-live-secret-long'})});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${app.server.address().port}`;app.config.APP_ORIGIN=base;owner=await signup('Owner');other=await signup('Other');});
after(async()=>app.close());
test('music schema installed without replacing existing tables',()=>{assert.equal(app.db.get('SELECT COUNT(*) n FROM migrations WHERE version IN (1,2)').n,2);assert.equal(app.db.get('SELECT COUNT(*) n FROM users').n,2);});
test('music and operator connection APIs require authorization',async()=>{assert.equal((await req('/api/music',undefined,null)).status,401);assert.equal((await req('/api/admin/bunny-check',{})).status,403);assert.equal((await req('/api/admin/music')).status,403);});
test('music mutations require CSRF and an explicit payer-confirmation step',async()=>{assert.equal((await req('/api/music',{payer:'venue',zones:1,confirm:true},owner,false)).status,403);assert.equal((await req('/api/music',{payer:'venue',zones:1})).status,400);assert.equal((await req('/api/music',{payer:'platform',zones:1,confirm:true})).status,400);});
test('sponsor request persists but cannot self-approve, charge or activate music',async()=>{const r=await req('/api/music',{payer:'sponsor',zones:1,confirm:true,status:'approved',provider:'fake',fundingReference:'fake'});assert.equal(r.status,201);requestId=r.body.id;assert.equal(r.body.status,'requested');assert.equal(r.body.paymentTaken,false);assert.equal(r.body.platformFundingCommitted,false);assert.equal(r.body.musicLive,false);const row=app.db.get('SELECT * FROM music_requests WHERE id=?',requestId);assert.equal(row.provider,'');assert.equal(row.funding_reference,'');});
test('duplicate enrollment is rejected rather than purchasing multiple services',async()=>{assert.equal((await req('/api/music',{payer:'venue',zones:1,confirm:true})).status,409);assert.equal(app.db.get('SELECT COUNT(*) n FROM music_requests').n,1);});
test('requests are tenant scoped and nonowners cannot choose a payer',async()=>{assert.equal((await req('/api/music',undefined,other)).body.requests.length,0);assert.equal((await req('/api/music/'+requestId+'/cancel',{},other)).status,404);app.db.run('INSERT INTO members VALUES(?,?,?)',owner.venue,other.id,'manager');assert.equal((await req('/api/music',{payer:'venue',confirm:true,zones:1},{...other,venue:owner.venue})).status,403);});
test('approval requires operator permission, sponsor, funding, license and valid expiry',async()=>{const data={id:requestId,decision:'approve',provider:'Licensed test provider',fundingReference:'private-funding',licenseReference:'private-license',validUntil:Date.now()+86400000,confirm:true};assert.equal((await req('/api/admin/music/review',data)).status,403);app.db.run("UPDATE users SET platform_role='admin' WHERE id=?",owner.id);assert.equal((await req('/api/admin/music/review',data)).status,400);for(const key of ['provider','fundingReference','licenseReference']){assert.equal((await req('/api/admin/music/review',{...data,sponsorName:'Sponsor',[key]:''})).status,400);}assert.equal((await req('/api/admin/music/review',{...data,sponsorName:'Sponsor',validUntil:1})).status,400);assert.equal((await req('/api/admin/music/review',{...data,sponsorName:'Sponsor',confirm:false})).status,400);const r=await req('/api/admin/music/review',{...data,sponsorName:'Sponsor'});assert.equal(r.status,200);assert.equal(r.body.musicLive,false);assert.equal(r.body.paymentTaken,false);});
test('venue status never exposes private funding/license references',async()=>{const r=await req('/api/music');assert.equal(r.body.requests[0].status,'approved');assert.ok(!JSON.stringify(r.body).includes('private-funding'));assert.ok(!JSON.stringify(r.body).includes('private-license'));assert.equal(r.body.musicLive,false);});
test('music requests do not alter TV billing, commissions or hardware eligibility',()=>{assert.equal(app.db.get('SELECT plan FROM venues WHERE id=?',owner.venue).plan,'free');for(const name of ['orders','ledger','contracts','billing_requests'])assert.equal(app.db.get(`SELECT COUNT(*) n FROM ${name}`).n,0);});
test('cancelling a setup request permits a replacement without cancelling external accounts',async()=>{const r=await req('/api/music/'+requestId+'/cancel',{});assert.equal(r.status,200);assert.match(r.body.message,/does not cancel/);const replacement=await req('/api/music',{payer:'venue',zones:2,confirm:true});assert.equal(replacement.status,201);assert.equal(replacement.body.musicLive,false);});
test('missing Bunny credentials yield real pending diagnostics, not connected status',async()=>{const r=await req('/api/admin/bunny-check',{resolution:720});assert.equal(r.status,200);assert.equal(r.body.readyForPlayerTest,false);assert.equal(r.body.checks[0].status,'pending');assert.equal(r.body.actualPlaybackTested,false);});
test('new UI modules are served through the existing application',async()=>{for(const path of ['/activation.mjs','/activation.css']){const r=await fetch(base+path);assert.equal(r.status,200);}const music=await fetch(base+'/music',{headers:{Cookie:owner.cookie}});assert.equal(music.status,200);assert.match(await music.text(),/MIXXPLAY/);});
