"""First-use guidance with real saved state in the disposable pilot fixture."""
from playwright.sync_api import expect
import sqlite3


def pilot_checks(page, context, base, database, out, passed):
    setup=page.locator('[data-venue-setup]')
    expect(setup).to_contain_text('Get your first screen playing.')
    expect(setup.locator('[data-setup-step="pair"]')).to_have_attribute('data-ready','false')
    expect(page.locator('.room-control,.stats')).to_have_count(0)
    page.screenshot(path=str(out/'pilot-home-desktop.png'),full_page=True)
    setup.locator('[data-page="mixx"]').click()
    page.locator('[data-action="world"][data-id="bourbon"]').click()
    expect(page.locator('[data-action="apply-mix"]')).to_contain_text('Save & pair a TV')
    page.route('**/api/venue',lambda route: route.fulfill(status=503,content_type='application/json',body='{"error":"Save temporarily unavailable."}') if route.request.method=='PATCH' else route.continue_())
    page.locator('[data-action="apply-mix"]').click()
    expect(page.locator('#toast')).to_contain_text('Save temporarily unavailable.')
    expect(page.locator('#dialog')).not_to_be_visible()
    expect(page.locator('[data-action="world"][data-id="bourbon"]')).to_have_attribute('aria-pressed','true')
    page.unroute('**/api/venue')
    page.locator('[data-action="apply-mix"]').click()
    expect(page.locator('#dialog')).to_be_visible()
    venue_id=page.evaluate("localStorage.getItem('mixx-venue')")
    venue=context.request.get(base+'/api/venue',headers={'X-Venue-Id':venue_id}).json()
    assert venue['venue']['mix']['worlds']=={'bourbon':'normal'}
    page.get_by_role('button',name='Close dialog',exact=True).click()
    page.locator('nav [data-page="home"]').click()
    expect(setup.locator('[data-setup-step="play"]')).to_contain_text('Bourbon')
    expect(setup.locator('[data-setup-step="play"]')).to_have_attribute('data-ready','false')
    passed('First-use Home leads to real actions; Save & pair persists the chosen MIXX and a failed save keeps the draft without opening pairing')

    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth<=innerWidth')
    setup.locator('.venue-setup-help summary').click()
    expect(setup.locator('.venue-setup-help')).to_contain_text('It does not grant venue remote access.')
    page.screenshot(path=str(out/'pilot-home-mobile.png'),full_page=True)
    setup.locator('[data-action="pair"]').click()
    expect(page.locator('#dialog [name="code"]')).to_be_visible()
    assert page.locator('#dialog').evaluate('(el)=>el.scrollWidth<=el.clientWidth')
    page.screenshot(path=str(out/'pilot-pairing-mobile.png'),full_page=True)
    page.get_by_role('button',name='Close dialog',exact=True).click()
    passed('First-use guidance and pairing fit a phone and explain the difference between venue remote access and a public TV QR')

    session=context.request.get(base+'/api/session').json()
    with sqlite3.connect(database) as db:db.execute("UPDATE members SET role='viewer' WHERE user_id=?",(session['user']['id'],))
    page.set_viewport_size({'width':1440,'height':1050});page.reload()
    expect(setup).to_contain_text('View only.')
    expect(setup.locator('[data-action="pair"]')).to_be_disabled()
    setup.locator('[data-page="mixx"]').click()
    for selector in ['[data-action="save-mix"]','[data-action="apply-mix"]','[data-action="world"][data-id="bourbon"]']:
        expect(page.locator(selector)).to_be_disabled()
    page.locator('nav [data-page="tvs"]').click()
    expect(page.locator('[data-action="pair"]').first).to_be_disabled()
    with sqlite3.connect(database) as db:db.execute("UPDATE members SET role='owner' WHERE user_id=?",(session['user']['id'],))
    page.reload()
    settings=page.locator('nav [data-stream-settings]')
    if not settings.evaluate('(el)=>el.open'):settings.locator('summary').click()
    passed('Viewer first-use, MIXX and TV screens expose inspection without enabled pairing or playback mutation controls')
